title: caioherrera
email: caio.herrera@outlook.com
description: Página onde compartilharei meus estudos e tópicos que achar interessante.

github_username: caioherrera
url: "https://caioherrera.github.io"

theme: jekyll-theme-minimal
